
Vagrant.configure("2") do |config|

  # ---------------SERVER---------------
    config.vm.synced_folder ".", "/vagrant"
    config.vm.define "kcarawayS" do |server|
      server.vm.box = "centos/8"
      server.vm.hostname = "kcarawayS"
      server.vm.box_check_update = false
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
        vb.cpus = 1
        vb.name = "kcarawayS"
      end
      server.vm.provision "shell", path: "./scripts/script.sh"
    end
  end
  