
Vagrant.configure("2") do |config|

# ---------------SERVER---------------
  config.vm.define "server" do |server|
    server.vm.box = "centos/8"
    server.vm.hostname = "server"
    server.vm.box_check_update = false
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "server"
    end

    server.vm.provision "shell", inline: <<-SHELL
      sudo dnf --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos -y
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server' K3S_TOKEN='token' K3S_KUBECONFIG_MODE=644 K3S_NODE_NAME="P1 SERVER"  sh -s - --flannel-backend none
    SHELL
  end

# ---------------SERVER-WORKER---------------
  config.vm.define "worker" do |worker|
    worker.vm.box = "centos/8"
    worker.vm.hostname = "worker"
    worker.vm.box_check_update = false
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "worker"
    end

    worker.vm.provision "shell", inline: <<-SHELL
      sudo dnf --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos -y
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='agent' K3S_TOKEN='token' K3S_URL=https://192.168.56.110:6443 sh -s - --flannel-backend none
    SHELL
  end

end
